include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/CreationSuiteBuildSettings.cmake")

function(configure_creation_shared_llvm APP_PREFIX APP_DISPLAY_NAME)
    creation_suite_init_build_settings()
    option(${APP_PREFIX}_ENABLE_SCRIPTING "Build ${APP_DISPLAY_NAME}'s LLVM-backed language host layer" ON)

    if(NOT ${APP_PREFIX}_ENABLE_SCRIPTING)
        return()
    endif()

    set(_local_vcpkg_dir "${CMAKE_SOURCE_DIR}/vcpkg_installed/x64-windows")
    set(_apps_engine_vcpkg_dir "${CMAKE_SOURCE_DIR}/../CreationEngine/vcpkg_installed/x64-windows")
    set(_suite_apps_engine_vcpkg_dir "${CREATION_SUITE_REPO_ROOT}/apps/CreationEngine/vcpkg_installed/x64-windows")

    if(DEFINED CE_LLVM_VCPKG_DIR AND EXISTS "${CE_LLVM_VCPKG_DIR}")
        set(_llvm_root "${CE_LLVM_VCPKG_DIR}")
    elseif(EXISTS "${_local_vcpkg_dir}")
        set(_llvm_root "${_local_vcpkg_dir}")
    elseif(EXISTS "${_apps_engine_vcpkg_dir}")
        set(_llvm_root "${_apps_engine_vcpkg_dir}")
    elseif(EXISTS "${_suite_apps_engine_vcpkg_dir}")
        set(_llvm_root "${_suite_apps_engine_vcpkg_dir}")
    else()
        message(STATUS "${APP_DISPLAY_NAME}: LLVM install not found; disabling LLVM JIT scripting layer for this build. "
                        "Set -DCE_LLVM_VCPKG_DIR=<path to a vcpkg_installed/x64-windows tree containing the custom LLVM build> to point at one explicitly.")
        set(${APP_PREFIX}_ENABLE_SCRIPTING OFF PARENT_SCOPE)
        return()
    endif()

    set(${APP_PREFIX}_LLVM_ROOT "${_llvm_root}" PARENT_SCOPE)
    list(APPEND CMAKE_PREFIX_PATH "${_llvm_root}")
    set(CMAKE_PREFIX_PATH "${CMAKE_PREFIX_PATH}" PARENT_SCOPE)
    find_package(LLVM CONFIG REQUIRED)
    set(LLVM_FOUND "${LLVM_FOUND}" PARENT_SCOPE)
    set(LLVM_DIR "${LLVM_DIR}" PARENT_SCOPE)
    set(LLVM_INCLUDE_DIRS "${LLVM_INCLUDE_DIRS}" PARENT_SCOPE)
    set(LLVM_DEFINITIONS "${LLVM_DEFINITIONS}" PARENT_SCOPE)
    set(LLVM_PACKAGE_VERSION "${LLVM_PACKAGE_VERSION}" PARENT_SCOPE)
    message(STATUS "${APP_DISPLAY_NAME}: using LLVM ${LLVM_PACKAGE_VERSION} from ${_llvm_root}")
endfunction()
