if(MSVC)
    add_compile_options("/FS")
endif()

add_subdirectory(AssetSystem)
add_subdirectory(Services)
add_subdirectory(UI)
add_subdirectory(NodeSystem)
add_subdirectory(MaterialSystem)
add_subdirectory(Interop)
add_subdirectory(VFS)
add_subdirectory(JuceDocking)
add_subdirectory(Timeline)
add_subdirectory(Video)
add_subdirectory(OfxHost)
add_subdirectory(NodeEditorUI)
